services:
  web:
    image: loredcast/filewizard:latest
    restart: unless-stopped
    build:
      context: .
      target: full-final # Change to 'full-final' or 'small-final' as needed
    
    environment:
      - LOCAL_ONLY=True # set to False to enable OIDC auth (requires configuration in settings.yml)
      - SECRET_KEY= <REDACTED>
      - UPLOADS_DIR=/app/uploads # directory structure INSIDE the container, not on host
      - PROCESSED_DIR=/app/processed
      - OMP_NUM_THREADS=1
      - DOWNLOAD_KOKORO_ON_STARTUP=true

    volumes:
      # Mount local directories and files into the container for persistence
      - <VOLUME>
      - <VOLUME>
      - <VOLUME>

#    ports:
#      - "127.0.0.1:6969:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filewizard.rule=Host(`filewizard.<HOST>.example.org`) || Host(`filewizard.<HOST>.example.org`)"
      - "traefik.http.routers.filewizard.entrypoints=websecure"
      - "traefik.http.routers.filewizard.tls=true"
      - "traefik.http.services.filewizard.loadbalancer.server.port=8000"
    networks:
      - proxy

networks:
  proxy:
    external: true
