#!/bin/bash
# Seal a VM so it can be converted into a Proxmox template and cloned.
#
# Run this ON the VM being turned into a template, as root:
#     sudo ~/Scripts/sealTemplate/sealTemplate.sh
#
# It strips the machine's IDENTITY (hostname, machine-id, ssh host keys, cloud-init state)
# and its accumulated per-host STATE (metrics, log positions, tailscale node, backup
# scripts, cron), then powers off. What survives is the generic parts: packages, repos,
# the /home/yasir checkout, /root/.ssh/<KEY>, and the container set.
#
# It ends with `poweroff`, on purpose. The ssh host keys are deleted in the final step,
# so the box is unreachable over ssh from that moment on — leaving it running would just
# strand it. --no-poweroff exists for inspection but leaves you on the console only.
#
# WHY EACH WIPE IS HERE: every one of these was a real failure during the 2026-08-06/07
# build of the first template. See Scripts/starterScript/starterScript.sh for the other
# half of the story — what gets rebuilt per-clone.

set -uo pipefail

POWEROFF=1
FORCE=0
for a in "$@"; do
    case "$a" in
        --no-poweroff) POWEROFF=0 ;;
        --force)       FORCE=1 ;;
        -h|--help)     sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "unknown argument: $a" >&2; exit 2 ;;
    esac
done

note() { printf '  %s\n' "$*"; }
HOME_DIR="${SUDO_USER:+/home/$SUDO_USER}"
HOME_DIR="${HOME_DIR:-/home/yasir}"
HOST="$(hostname)"

echo "=== preflight ==="
# Must be ROOT, and not merely via `sudo somecommand`. The wipes below use globs like
# /var/lib/tailscale/* — those are expanded by the CALLING shell, so running them as an
# unprivileged user against a root-only directory matches nothing, leaves the glob
# literal, and `rm -f` swallows the error. The wipe then silently does nothing while
# reporting success. That exact bug shipped a "sealed" image with its tailscale node
# identity and alloy read-positions intact.
if [ "$(id -u)" -ne 0 ]; then
    echo "Must run as root (sudo $0) — see the comment above about globs." >&2
    exit 1
fi

# Guard against sealing a LIVE host by accident. This script destroys machine identity;
# running it on, say, docker0 would be a very bad afternoon. A production host is in
# ~/hosts and/or has joined the tailnet; the template deliberately is neither.
LIVE=0
if [ -f "$HOME_DIR/hosts" ] && grep -qiE "^[0-9.]+[[:space:]]+$HOST([[:space:]]|$)" "$HOME_DIR/hosts"; then
    note "WARNING: '$HOST' appears in $HOME_DIR/hosts — that means it is a real fleet host."
    LIVE=1
fi
if tailscale status --json 2>/dev/null | grep -q '"BackendState":"Running"'; then
    note "WARNING: tailscale is authenticated — templates are installed but never joined."
    LIVE=1
fi
if [ "$LIVE" -eq 1 ] && [ "$FORCE" -eq 0 ]; then
    echo "This looks like a LIVE host, not a template candidate. Re-run with --force if you are sure." >&2
    exit 1
fi
note "sealing '$HOST'"

echo
echo "=== per-host artifacts (regenerated by starterScript on each clone) ==="
# These are named after THIS host. Left in place, every clone inherits scripts and a cron
# entry pointing at the template's name, and backs itself up to the wrong NAS folder.
NAME="${HOST^}"
for f in "$HOME_DIR/Scripts/backupToStore/backup${NAME}.sh" \
         "$HOME_DIR/Scripts/restoreFromStore/restore${NAME}.sh" \
         "$HOME_DIR/Scripts/rsyncLocalScripts/${HOST}SyncJobs.sh"; do
    [ -e "$f" ] && { rm -f "$f"; note "removed $(basename "$f")"; }
done
if crontab -l 2>/dev/null | grep -q "SyncJobs.sh"; then
    crontab -l 2>/dev/null | grep -v "SyncJobs.sh" | crontab -
    note "removed root cron SyncJobs entry"
fi

echo
echo "=== swap ==="
# A template must not ship a swapfile: it is N gigabytes of zeroes that inflate the vzdump
# for nothing. starterScript recreates it per-clone, sized min(RAM, 4G).
if [ -f /swapfile ]; then
    swapoff /swapfile 2>/dev/null
    rm -f /swapfile
    sed -i '\|^/swapfile|d' /etc/fstab
    note "removed /swapfile and its fstab entry"
else
    note "no /swapfile present"
fi

echo
echo "=== per-host service state ==="
# Stopped only so the wipes stick — these three hold their data directories open and would
# recreate the files a second later. They stay `enabled`, so clones start them at boot.
systemctl stop prometheus alloy tailscaled 2>/dev/null

rm -rf /var/lib/prometheus/*
# node-exporter/ is the textfile collector directory and is SHIPPED BY THE PACKAGE. The
# wipe above takes it with the TSDB, and without it node-exporter logs an error every 15
# seconds forever on every clone. Recreate it here so the image is not shipped broken.
install -d -o root -g root -m 755 /var/lib/prometheus/node-exporter
note "prometheus TSDB wiped, textfile collector dir recreated"

# ONLY data/ — /var/lib/alloy is alloy's HOME directory and also holds .bashrc/.profile/
# .cache. Wiping the whole thing deletes the user's dotfiles for no reason.
rm -rf /var/lib/alloy/data/* /var/lib/alloy/.cache/* 2>/dev/null
note "alloy read positions cleared (home dotfiles kept)"

# Node identity. Two hosts sharing tailscaled.state fight over one tailnet node.
rm -rf /var/lib/tailscale/*
note "tailscale node identity cleared"

echo
echo "=== logs and caches ==="
journalctl --rotate >/dev/null 2>&1
journalctl --vacuum-time=1s >/dev/null 2>&1
truncate -s0 /var/log/wtmp /var/log/btmp 2>/dev/null
apt-get clean
note "journal vacuumed, apt cache cleared, wtmp/btmp truncated"

echo
echo "=== home directory ==="
# Ship WITHOUT a .bashrc so starterScript installs the fleet baseline from
# Store/archetypes/FRESHVM/.bashrc_startup on each clone rather than inheriting a stale copy.
rm -f "$HOME_DIR/.bashrc" "$HOME_DIR"/.bashrc.pre-starter.* "$HOME_DIR/.bash_history"
rm -f /root/.bash_history
note "removed ~/.bashrc, its pre-starter backups, and shell history"

if [ -d "$HOME_DIR/.git" ]; then
    DIRTY="$(cd "$HOME_DIR" && sudo -u "${SUDO_USER:-yasir}" git status --porcelain 2>/dev/null | wc -l)"
    if [ "$DIRTY" -ne 0 ]; then
        note "WARNING: $DIRTY uncommitted change(s) in $HOME_DIR — they will be baked into the image"
    else
        note "repo clean"
    fi
fi

echo
echo "=== identity (LAST — ssh dies here) ==="
# cloud-init is the load-bearing one. Its status is 'done' on a configured box, so without
# this it SKIPS on first boot of the clone and the clone comes up still carrying this
# host's name — which then makes starterScript generate backup<TemplateName>.sh artifacts.
cloud-init clean --logs
note "cloud-init reset (status will read 'not started')"

truncate -s0 /etc/machine-id
rm -f /var/lib/dbus/machine-id
note "machine-id cleared (a stale one makes DHCP hand clones the same lease)"

# ABSOLUTELY LAST. sshd is socket-activated: it spawns per connection, so the moment these
# are gone every NEW ssh connection fails with kex_exchange_identification. Doing this
# earlier strands you mid-seal. If you are locked out anyway, qemu-guest-agent is still
# running: `qm guest exec <vmid> -- /bin/bash -c '...'` from the hypervisor.
rm -f /etc/ssh/ssh_host_*
note "ssh host keys removed — no further ssh logins possible"

sync

echo
if [ "$POWEROFF" -eq 1 ]; then
    echo "=== powering off ==="
    echo "  Next, on the hypervisor:"
    echo "    qm template <vmid>"
    echo "    qm clone <vmid> <newid> --name <newhost> --full 1"
    echo "  Then on the clone: git pull FIRST, then ~/Scripts/starterScript/starterScript.sh"
    sleep 2
    poweroff
else
    echo "=== done (--no-poweroff) ==="
    echo "  ssh is dead on this box now. Shut it down from the hypervisor:  qm shutdown <vmid>"
fi
