name: Local Agent
version: 1.1.0
schema: v1
models:
  # Qwen2.5-coder is the go-to (within my hardware limitations) for general use for programming.
  - name: Qwen2.5-Coder 7B
    provider: ollama
    model: qwen2.5-coder:7b
    apiBase: "https://ollama.<HOST>.example.org"
    roles:
      - autocomplete
      - apply
      - chat
      - edit
  # Qwen2.5-coder is the go-to (within my hardware limitations) for general use for programming.
  - name: Qwen2.5-Coder 7B -- local
    provider: ollama
    model: qwen2.5-coder:7b
    apiBase: "http://localhost:11434"
    roles:
      - autocomplete
      - apply
      - chat
      - edit
    
  # Nomic embed is the go-to (within my hardware limitations) for embedding text.
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
